apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hu2r5vlk2-nodejs 
  janus-idp.io/tekton: hu2r5vlk2-nodejs
  backstage.io/kubernetes-id: hu2r5vlk2-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hu2r5vlk2-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml