apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hu2r5vlk2-nodejs
  janus-idp.io/tekton: hu2r5vlk2-nodejs
  backstage.io/kubernetes-id: hu2r5vlk2-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hu2r5vlk2-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
